name: Build Plugin
run-name: ${{ github.actor }} triggered this job
on:
  workflow_dispatch:
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Download unzip
        run: |
          wget https://download.agora.io/sdk/release/uni-app-sdk-android.zip
          unzip uni-app-sdk-android.zip

      - uses: actions/checkout@v3
        with:
          path: Agora-Uniapp-SDK
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Modify gradle
        run: |
          echo "project(':uniplugin_agora_rtc').projectDir = new File('../Agora-Uniapp-SDK', 'android')" >> settings.gradle
        working-directory: Android-SDK@3.6.18.81676_20230117/UniPlugin-Hello-AS
          
      - name: Gradle build
        run: |
          sh gradlew :uniplugin_agora_rtc:assembleRelease
        working-directory: Android-SDK@3.6.18.81676_20230117/UniPlugin-Hello-AS
        
      - uses: actions/upload-artifact@v3
        with:
          name: AgoraRtcUniPlugin
          path: "Android-SDK@3.6.18.81676_20230117/UniPlugin-Hello-AS/**/*.aar"
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Download unzip
        run: |
          wget https://download.agora.io/sdk/release/uni-app-sdk-ios.zip
          unzip uni-app-sdk-ios.zip
          
      - uses: actions/checkout@v3
        with:
          path: Agora-Uniapp-SDK
          
      - name: Modify Podfile
        run: |
          pod init
          sed "s/# Pods for .*/pod 'AgoraRtcUniPlugin', :path => '\.\.\/Agora-Uniapp-SDK\/ios'/g" Podfile > tmp
          mv tmp Podfile
        working-directory: SDK/HBuilder-uniPluginDemo
          
      - name: Xcodebuild build
        run: |
          pod install
          xcodebuild -workspace ./HBuilder-uniPlugin.xcworkspace -scheme AgoraRtcUniPlugin -sdk iphoneos -configuration "Release" build
        working-directory: SDK/HBuilder-uniPluginDemo
      
      - uses: actions/upload-artifact@v3
        with:
          name: AgoraRtcUniPlugin
          path: "SDK/HBuilder-uniPluginDemo/*.framework"
